### ISSUE TITLE
어째서 github pages를 사용하지 않습니까?

### ISSUE THREAD

**Issue by vbalien** [KwonTF/kwontf#36]
# 빌드하면 정적페이지 아닌가요?

![image](https://user-images.githubusercontent.com/4590714/68093234-d9150280-fed6-11e9-945e-221ccbc3c68e.png)

**Comment by niceb5y** [comment]
![18d035a3d6a92f5a3d983052d7475abcf8873bd03da7b57ff454d3bc68a2a7c8f2adbdcd066680ff7d2d3ccc11db377ef208ca91a62a2f078c0c179030d7e0ca495a3c549274a9210192cec52390f906e5772571f9e1279d570f07e17e626cf572332d34ebd7867e68de40d78504c352](https://user-images.githubusercontent.com/1621389/68180710-0695a500-ffd8-11e9-97a4-97c892ecb027.png)
음.... 지나가던 사람인데, 어쨌든 이거 만드는 데 기여는 했으니 설명하자면요....

1. 정적 페이지 빌딩은 맞습니다.
어쨌든 http://kwontf.netlify.com 로 뿌려지긴 합니다. 

2. 그럼에도 github pages를 쓰지 않았던 이유는 아마...
그 당시에 github pages가 custom domain에 대해 https를 지원하지 않아서입니다.

**Comment by vbalien** [comment]
궁금증이 해결되었습니다. :)
github pages으로 이동할 이유가 없으니 이슈를 닫겠습니다.

![image](https://user-images.githubusercontent.com/4590714/68183189-f6cd8f00-ffde-11e9-87e9-fbd07999ec0f.png)
