### ISSUE TITLE
dependabot의 풀리퀘스트를 수락하십시오.

### ISSUE THREAD

**Issue by vbalien** [KwonTF/kwontf#37]
dependabot의 풀리퀘스트를 수락하여 종속 패키지를 업데이트하고 머지된 브랜치를 제거하세요.

현재 브랜치는 dependabot때문에 매우 더러우며, 보안이슈가 많은 구버전의 패키지를 사용중입니다.
![image](https://user-images.githubusercontent.com/4590714/68180164-fa104d00-ffd5-11e9-9014-b0d6e8eb47c0.png)

![image](https://user-images.githubusercontent.com/4590714/68180188-157b5800-ffd6-11e9-8ef9-682e38a0afb6.png)

**Comment by niceb5y** [comment]
해결했답니다.
